import type { Metadata } from 'next'
import '../globals.css'
import { Sarpanch } from 'next/font/google'
import Navbar from '../../components/Navbar'


const sarpanch = Sarpanch({ weight: ['400', '500', '600', '700', '800', '900'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'New Rent Car | Alquiler de Vehículos',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.svg'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sarpanch.className} overflow-x-hidden`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}

